name: Compile new.pwn to new.amx

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Download project
        uses: actions/checkout@v4

      - name: Build Pawn Compiler
        run: |
          git clone --depth 1 https://github.com/pawn-lang/compiler.git pawncompiler

          cd pawncompiler

          mkdir build
          cd build

          cmake ../source/compiler -DCMAKE_BUILD_TYPE=Release
          cmake --build . --target pawncc -j2

          cd ../../

      - name: Compile new.pwn
        run: |
          ./pawncompiler/build/pawncc \
            ./gamemodes/new.pwn \
            -i./pawno/include \
            -i./gamemodes \
            -i. \
            -o./gamemodes/new.amx

      - name: Check new.amx
        run: |
          echo "Checking AMX..."
          ls -lh ./gamemodes/new.amx

      - name: Upload new.amx
        uses: actions/upload-artifact@v4
        with:
          name: new-amx
          path: ./gamemodes/new.amx
