name: Compile NAVARA Pawn

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ cmake make git

      - name: Prepare mxINI
        run: |
          cp ./pawno/include/mxINI.inc ./pawno/include/mxini.inc

      - name: Build Pawn Compiler
        run: |
          git clone --depth 1 https://github.com/pawn-lang/compiler.git pawncompiler

          cd pawncompiler
          mkdir build
          cd build

          cmake ../source/compiler \
            -DCMAKE_BUILD_TYPE=Release

          cmake --build . --target pawncc -j2

          cd ../../

          chmod +x ./pawncompiler/build/pawncc

      - name: Check files
        run: |
          echo "Checking files..."
          ls -lh ./gamemodes/new.pwn
          ls -lh ./pawno/include/mxINI.inc
          ls -lh ./pawno/include/mxini.inc

      - name: Compile new.pwn
        run: |
          ./pawncompiler/build/pawncc \
            ./gamemodes/new.pwn \
            -i./pawno/include \
            -i./gamemodes \
            -i. \
            -Z+ \
            -o./gamemodes/new.amx

      - name: Check AMX
        run: |
          echo "AMX created successfully:"
          ls -lh ./gamemodes/new.amx

      - name: Upload new.amx
        uses: actions/upload-artifact@v4
        with:
          name: NAVARA-new-amx
          path: ./gamemodes/new.amx
